Patch myocamlbuild.ml to not use internal ocamlbuild function.
I was running into the following error:

    ocamlbuild -no-links -tag debug client_server_test.byte
    + /usr/local/bin/ocamlopt.opt unix.cmxa -I /usr/local/lib/ocaml/ocamlbuild /usr/local/lib/ocaml/ocamlbuild/ocamlbuildlib.cmxa myocamlbuild.ml /usr/local/lib/ocaml/ocamlbuild/ocamlbuild.cmx -o myocamlbuild
    File "myocamlbuild.ml", line 12, characters 4-76:
    Error: This expression has type Lexing.lexbuf
           but an expression was expected of type
             Ocamlbuild_pack.Loc.source = string

The interface of an internal ocamlbuild function that was used to
implement [find_packages] must have changed. I replaced it with a simple
reimplementation using the standard library.